### PR TITLE
Use ServiceLoader for yaml

### PR DESCRIPTION
**Pull request by SentryMan**
now people can plug their own yaml parsers.
fixes part of #41

### CODE REVIEW

**Comment by SentryMan** [comment]
hmm

**Comment by SentryMan** [comment]
perhaps I've become too comfortable with circles. But this'll work to extract the yml out of the config module so it can be excluded.

**Comment by rob-bygrave** [comment]
I don't think this change is justified.  The premise is the YamlSimpleLoader is large enough to justify removing it out into a separate module.

It's 300 lines, I don't think this justifies pulling it out into a separate module etc.

**Comment by SentryMan** [comment]
It saves like 10kb if we take it out yeah

**Pull request closed without merging**
