### PR TITLE
Add a flag to determine file/resource bitwise loading 

### PR DESCRIPTION
**Pull request by SentryMan**
Currently, we make two resource calls for one resource 99% of the time.

a resource call is nontrivial in cost. We can do interpolation all day long on giant lists of key values but make a file call or classpath load and it's a solid 30ms for each one until the disk cache gets happy.

- Detect the `config.single.load` property to not use bitwise to load files/resources

### CODE REVIEW

**Comment by rob-bygrave** [comment]
This is a breaking change in behaviour.

**Comment by SentryMan** [comment]
wait is it actually?

**Comment by rbygrave** [comment]
avaje-config has more than 60k downloads per month from maven central. There are a **_lot_** of apps that have it as a dependency and using its existing behaviour.

There are 2 types of breaking changes. A type that produce a nice exception like "This feature has been removed, please do X" ... and the second type that are **_subtle breaking changes_** where we don't actually know what how an app will be impacted or how the change in behaviour is actually going to be observed [like in this case].

This is a breaking change that is that subtle change in behaviour type. These are the most terrible type of breaking change in terms of how they impact users.

> make two resource calls

One is a classpath resource and one is a file resource. e.g. application.properties as both a classpath resource and local file which I suspect is not that uncommon a pattern. 

> 99% of the time.

Of the thousands of applications out there using avaje-config today, how do we come up with 99%?  How do we have any clue as to how many apps this change will actually break?

**Comment by SentryMan** [comment]
> How do we come up with 99% 

The `|` operator runs both branches no matter the boolean result of the left condition. So I suppose I should have said 100% of the time.

**Comment by rbygrave** [comment]
You do understand this means that it just won't load `file:application.properties` when there is application.properties in the classpath.  

You understand that any app expecting `file:application.properties` to load is now broken by this change.

**Comment by SentryMan** [comment]
> You do understand this means that it just won't load file:application.properties when there is application.properties in the classpath.

yes

**Comment by rbygrave** [comment]
We have no idea how many apps will be broken by this right.

**Comment by SentryMan** [comment]
I will make a flag to enable then to make this opt-in

**Comment by SentryMan** [comment]
@rbygrave how is this?

**Comment by SentryMan** [comment]
@rbygrave I'm good with this (unless you want to name the flag something else)

**Comment by SentryMan** [comment]
@rbygrave the ability to cut resource loading time by half is pretty useful wouldn't you agree? I've made it an opt-in feature as well so it doesn't break existing apps.

**Comment by rbygrave** [comment]
> to cut resource loading time by half 

I think that is not accurate. I think that is wildly off. Plus this isn't _actually compatible_ with the existing behaviour.

> and it's a solid 30ms for each one

I think this is specifically not accurate. Its a File.exists() check and that isn't 30ms for each one in practice.

So no, I'm not that interested in this change at this point.

**Comment by SentryMan** [comment]
> Plus this isn't actually compatible with the existing behaviour.

I made it a flag, with the current behavior as the default

**Comment by SentryMan** [comment]
>  Its a File.exists() check

Somehow I missed that, I guess I was under the impression that it was making a resource call

**Pull request closed without merging**
