### PR TITLE
Add Priority to `ConfigurationSource`

### PR DESCRIPTION
**Pull request by SentryMan**
adds priority to the Configuration source.

### CODE REVIEW

**Comment by agentgt** [comment]
See if we start going this route then we should probably consider getting rid of `load.properties`. This is the helidon and microprofile route. They don't allow chaining and you must list your resources all at the beginning. What they allow similar to `load.properties` is an `order` key value right on the resource but its value cannot have interpolation IIRC. https://microprofile.io/specifications/microprofile-config-2/

Chaining and then having priority order are at odds with each other. They require different data structures and different traversal making the core way more complicated.

I suppose we could have this special case but IMO I'm more for sunsetting `ConfigurationSource`.

**Comment by agentgt** [comment]
Interestingly in terms of exploring and backward compat could just keep `ConfigurationSource` and allow some way for an implementation to say only load me.

The idea being what Avaje currently does for its initial load could all be a `ConfigurationSource`.

The new URI stuff could all be put in a new `ConfigurationSource`. This is I think what @rbygrave Rob was explaining a comment of how to incorporate the newer URI model in.

So priority is too weak here. We may want to replace. So maybe label and priority where label is like a key and the default has key "default".... yeah this is getting nasty.

**Comment by SentryMan** [comment]
Adding a priority here is only to make using `ConfigurationSource` more predictable, as currently there isn't really a defined order to them. 

> getting rid of load.properties

Nah

> The new URI stuff could all be put in a new ConfigurationSource

Doesn't really fly well since `ConfigurationSource` source happens at the wrong time in the loading cycle. It runs after `load.properties` and all the configuration files are loaded and evaluated.

**Comment by agentgt** [comment]
> Adding a priority here is only to make using ConfigurationSource more predictable, as currently there isn't really a defined order to them.

The problem is that everyone always picks `Integer.MIN_VALUE` or `Integer.MAX_VALUE` if it is just some hard coded thing and not dynamic.

Consequently you will need to sort on a secondary value like the name to have predictable order... and guess what people do for that: `__PleaseLoadMeFirstExtension` (notice underscores).

A possible solution is to do what I did with Rainbow Gum where the source returns `boolean` indicating it ran it did not need a dependency that was missing. See: https://jstach.io/rainbowgum/io.jstach.rainbowgum/io/jstach/rainbowgum/spi/RainbowGumServiceProvider.Configurator.html#configure(io.jstach.rainbowgum.LogConfig,io.jstach.rainbowgum.spi.RainbowGumServiceProvider.Pass)

**Comment by SentryMan** [comment]
> The problem is that everyone always picks Integer.MIN_VALUE or Integer.MAX_VALUE if it is just some hard coded thing and not dynamic.

It's a default method, so I don't expect it to be used often, it's there for those rare times when you want something to run sooner.

**Comment by agentgt** [comment]
In theory there is a predictable order based on classpath. 

It is how `getResources` works. I stress the plural **`s`**.

That is also why Spring has `classpath://` and `classpath*://` (and ajave-config could have similar with URI loading).

**Comment by SentryMan** [comment]
> In theory there is a predictable order based on classpath.

It's deterministic sure, but I might want to change it manually. Fiddling with the cp sounds really boring

**Comment by agentgt** [comment]
Yes but it is weird because the consumer of the configuration source does not choose the order but rather the author of the configuration source.

If it was such a problem for the author they would just make their configuration source do everything. That is I fail to see it being a problem for the author.

It is a bigger problem for the consumer who might want to configure the order of several third party.

There is also just plain disable and enable. That seems like you could get double duty out of this integer with below zero being disabled.

Otherwise I just fail to see the value of adding to permanent API.

**Comment by SentryMan** [comment]
> Skill issue

Makes sense to me

**Pull request closed without merging**
